name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        run: pip install uv

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      - name: Install lint tools
        run: uv add --dev pylint

      - name: Run pylint
        run: uv run pylint src/searchess_ai
